# Week 1 Exercises

* The exercise below should be completed using tools provided by numpy arrays. 
* Do not use for or while loops, list comprehensions etc. 
* The code in each case can be written in fewer than 10 lines.

In [84]:
import numpy as np
%pylab inline

Populating the interactive namespace from numpy and matplotlib


## Exercise 1

* Write a function border(a) which takes as an argument an 2-dimensional numpy array a and returns an array obtained by adding a border of zeros to a.

In [85]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 1. Answer

In [86]:
def border(a):
    b = np.zeros((a.shape[0]+2,a.shape[1]+2),dtype = int)
    b[1:-1,1:-1] = a
    b
    return b # b is the matrix we want to return 
border(a)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  0],
       [ 0,  4,  5,  6,  7,  0],
       [ 0,  8,  9, 10, 11,  0],
       [ 0,  0,  0,  0,  0,  0]])

## Exercise 2

* Write a function row_split(a, k) which for a given 2-dimensional numpy array a and a positive integer k returns a tuple of two 2-dimensional numpy arrays: one consisting of the first k rows of a and the second consisting of the remaining rows.

In [87]:
a = np.arange(15).reshape(5, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### 2. Answer

In [88]:
def row_split(a,num):
    b = a[:num]
    c = a[num:]
    return b,c

In [89]:
print(row_split(a,3)[0])
print("\n")
print(row_split(a,3)[1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[ 9 10 11]
 [12 13 14]]


## Exercise 3

* Write a function n_smallest(a, n) which given a 1-dimensional numpy array a and an integer n returns an array with indices of n smallest elements of a

In [90]:
rng = np.random.default_rng(0) # initialize the random number generator
a = rng.integers(0, 100, 10)
print(a)

[85 63 51 26 30  4  7  1 17 81]


### 3. Answer

In [91]:
def n_smallest(a, n):
    return np.argsort(a)[:n]
n_smallest(a,3)

array([7, 5, 6])

## Exercise 4

* Write function checkers(n) which returns an $n \times n$  numpy array consisting of zeros and ones arranged in a checkerboard pattern. To check that this function works correctly, test it for both odd and even values of $n$.

In [92]:
a = np.zeros(5*5)
a[::2]=1
a.reshape(5,5)

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

### 4. Answer

In [93]:
def checkers(n):
    if n % 2 ==1:
        a = np.zeros(n*n)
        a[::2]=1
        b = a.reshape(n,n)
        return b
    else:
        mtx = np.zeros((6,6))
        a = np.zeros(6)
        ol = a.copy()
        ol[::2]=1 #101010
        el = a.copy()
        el[1::2]=1 # 010101

        mtx[::2] = ol # odd lines
        mtx[1::2] = el
        return mtx

### Test for # 4:

In [94]:
print("When n = 5: \n",checkers(5),"\n\n","When n = 6:\n",checkers(6))

When n = 5: 
 [[1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]] 

 When n = 6:
 [[1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1.]]


## Exercise 5

* Write a function sub_table(n) which returns an  numpy array with the subtraction table of numbers from 0 to $n-1$. The value in the row $i$ and column $j$ of the array should be the number $i-j$.

### 5. Answer

In [108]:
def sub_table(n):
    return np.subtract.outer(np.arange(n), np.arange(n))
sub_table(11)

array([[  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10],
       [  1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9],
       [  2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8],
       [  3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7],
       [  4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5,  -6],
       [  5,   4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,  -5],
       [  6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3,  -4],
       [  7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3],
       [  8,   7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2],
       [  9,   8,   7,   6,   5,   4,   3,   2,   1,   0,  -1],
       [ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1,   0]])

## Exercise 6

* If ${\bf v}$  and ${\bf w}$ are two vectors with $n$ coordinates, then their Euclidean distance  is given by the formula: 
$$d({\bf v},{\bf w}) = \sqrt{\sum_{i=1}^n (v_i -w_i)^2}$$

* Let $X$ be an $m\times n$ numpy array, and let ${\bf w}$ be a 1-dimensional array with $n$ entries. Write a function dist(X, w) which returns a 1-dimensional array with $m$ entries, such that the $i$-th entry is the distance between ${\bf w}$ and the $i$-th row of $X$.

In [96]:
X = np.arange(12).reshape(3, 4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
w = np.array([0, 1, 0, 1])
w

array([0, 1, 0, 1])

### 6. Answer

In [98]:
def dist(X,w):
    return np.sqrt(sum(square(X-w),axis = 1))
dist(X,w)

array([ 2.82842712, 10.19803903, 18.11077028])

In [99]:
# Note: axis=0 sum along the rows; axis=1 sum along the columns

## Exercise 7

* Write a function order_columns(a) which takes as an argument a 2-dimensional numpy array and returns an array obtained by reordering columns of $a$ according to the sum of their entries: the first column is the one where the sum of entries is the smallest, the last column is the one where the sum of entries is the largest.

In [112]:
def order_columns(a):
    return a[:,argsort(sum(a,axis=0))]

In [113]:
rng = np.random.default_rng(1) # initialize the random number generator
a = rng.integers(0, 6, (3,5))
a

array([[2, 3, 4, 5, 0],
       [0, 4, 5, 1, 1],
       [5, 2, 1, 4, 1]])

In [114]:
order_columns(a)

array([[0, 2, 3, 4, 5],
       [1, 0, 4, 5, 1],
       [1, 5, 2, 1, 4]])

## Exercise 8

* Write the function first_smaller(a, n) which takes as its argument a 1-dimensional numpy array $a$ and a number $n$ and returns the first entry of $a$ which is smaller than $n$. If such entry does not exist the function should return None.

### Answer for # 8

In [115]:
def first_smaller(a,n):
    try: 
        return a[a<n][0]
    except:
        return None

In [116]:
rng = np.random.default_rng(0) # initialize the random number generator
a = rng.integers(0, 100, 10) # array of 10 random integers 0 <= n < 100
a

array([85, 63, 51, 26, 30,  4,  7,  1, 17, 81])

### Test for # 8

In [117]:
# None situation
first_smaller(a,1)

In [118]:
# Not None situtation
first_smaller(a,50)

26